// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('C:/Projects/resume/src/components/HelloWorld.vue')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IMyIconsAuburn: typeof import('~icons/my-icons/auburn')['default']
    IMyIconsCgi: typeof import('~icons/my-icons/cgi')['default']
    IMyIconsCts: typeof import('~icons/my-icons/cts')['default']
    IMyIconsIllumicare: typeof import('~icons/my-icons/illumicare')['default']
  }
}

export { }
